// Optimize the full workforce photo set for web and emit a manifest.
// Reads ../traning and ../Photo (dedup by filename), resizes to 1100px wide,
// fixes EXIF orientation, writes public/images/gallery/ + src/lib/gallery.ts
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

const ROOT = path.resolve("..");
const SRC_DIRS = [path.join(ROOT, "traning"), path.join(ROOT, "Photo")];
const OUT_DIR = path.resolve("public/images/gallery");
const MANIFEST = path.resolve("src/lib/gallery.ts");
const EXTS = new Set([".jpg", ".jpeg", ".png"]);

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const seen = new Map(); // basename(lower) -> fullpath  (dedupe across folders)
  for (const dir of SRC_DIRS) {
    if (!existsSync(dir)) continue;
    for (const f of await readdir(dir)) {
      if (!EXTS.has(path.extname(f).toLowerCase())) continue;
      const key = f.toLowerCase();
      if (!seen.has(key)) seen.set(key, path.join(dir, f));
    }
  }

  const entries = [...seen.values()].sort();
  console.log(`Found ${entries.length} unique images. Optimizing...`);

  const out = [];
  let idx = 0;
  for (const src of entries) {
    idx++;
    const name = `g-${String(idx).padStart(3, "0")}.jpg`;
    try {
      await sharp(src)
        .rotate()
        .resize({ width: 1100, withoutEnlargement: true })
        .jpeg({ quality: 78, mozjpeg: true })
        .toFile(path.join(OUT_DIR, name));
      out.push(`/images/gallery/${name}`);
      if (idx % 20 === 0) console.log(`  ${idx}/${entries.length}`);
    } catch (e) {
      console.log(`  skip ${path.basename(src)}: ${e.message}`);
    }
  }

  const ts =
    `// AUTO-GENERATED by scripts/optimize-gallery.mjs — web-optimized workforce gallery\n` +
    `export const GALLERY_IMAGES: string[] = ${JSON.stringify(out, null, 2)};\n`;
  await writeFile(MANIFEST, ts, "utf8");
  console.log(`Done. ${out.length} images -> public/images/gallery/, manifest -> src/lib/gallery.ts`);
}

main().catch((e) => { console.error(e); process.exit(1); });
